version: "3.9"

services:
  front:
    image: patna/front:latest
    ports:
      - "8623:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET= 235a2df63aa5874d9b88a76a1c7208fe
      - NEXT_PUBLIC_HOST = api:8624
    networks:
      - pattana

networks:
  pattana:
    external:
      name: pattana